global using NewProject.Models;
global using NewProject.ViewModel;
global using Microsoft.AspNetCore.Mvc.Rendering;
global using System.ComponentModel.DataAnnotations;
global using Microsoft.AspNetCore.Mvc;
global using NewProject.Services;
global using Microsoft.EntityFrameworkCore;
global using NewProject.Data;
global using System.Diagnostics;